"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import { AnimatePresence, motion } from "motion/react";
import SplashScreen from "@/components/splash-screen";
import Navigation from "@/components/navigation/navigation";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const pathname = usePathname();
    const isHomePage = pathname === "/";
    const [isLoading, setLoading] = useState(true);

    // loading animation for 3s
    useEffect(() => {
        const timer = setTimeout(() => {
            setLoading(false);
        }, 3000);
        return () => clearTimeout(timer);
    }, []);

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden bg-black text-white`}
            >
                <AnimatePresence>
                    {/* Splash Screen */}
                    {isHomePage && isLoading ? (
                        <SplashScreen key={"loading"} />
                    ) : (
                        <motion.div>
                            <Navigation />
                            {/* Main Content */}
                            {children}
                        </motion.div>
                    )}
                </AnimatePresence>
            </body>
        </html>
    );
}
